Fixing encryption problems
Didstopia/PDFSharp pull request #17
Opened 2018-02-22 05:47 UTC by ronnyek

I went ahead and did a pretty rudimentary swap of MD5Managed for MD5 .netcore official library. I was able to open files with no security provider, or incorrect password and get expected exceptions, went ahead and added a known PDF to tests and was able to open file with provided password successfully.

2018-02-22 05:48 UTC, ronnyek commented
Admittedly, MD5Managed should be fully gutted, and not have two implementations of MD5 algorithms in place... but this shows things work this way

2018-02-22 07:30 UTC, Dids commented
Haven't yet had a chance to properly go over this, but I'm assuming this would fix #3?

2018-02-22 13:03 UTC, Dids requested changes

2018-02-22 13:03 UTC, Dids commented on Didstopia.PDFSharp.Tests/PDFSharpTests.cs
> +                Assert.Equal(ex.Message, "The specified password is invalid.");
These two parameters should be flipped, so it matches the assertion logic, but also to get rid of the following warning:

```
PDFSharpTests.cs(91,17): warning xUnit2000: The literal or constant value "The specified password is invalid." should be the first argument in the call to 'Assert.Equal(expected, actual)' in method 'TestEncryptionFailsProperly' on type 'PDFSharpTests'. [/home/travis/build/Didstopia/PDFSharp/Didstopia.PDFSharp.Tests/Didstopia.PDFSharp.Tests.csproj]
```

2018-02-22 19:01 UTC, ronnyek commented
Yep, this fixes #3. I can make those minor changes, and I can evaluate whether or not the MD5Managed even needs to be there as its now a full blown library in nuget

2018-02-23 03:36 UTC, ronnyek commented
There we go, still waiting for travis build. Ended up being able to just opt for usage of microsofts fully managed MD5 provider, and all appears to be well.

Updated equality checks, and resolved all resharper warnings other than the name of the test file, which was nitpicky.

2018-02-26 09:24 UTC, merged